### ISSUE TITLE
Evaluation code with pretrained for Table1,2,3.

### ISSUE THREAD

**Issue by taeyeopl** [yenchenlin/nerf-supervision-public#2]
Thanks for sharing the good work. 
I have some questions related to your results. 

Q1. Can you explain the details of the training process of GLU-Net[6], GoCor[12], PDC-Net[7]?? It was not mentioned how to train [6, 7, 12] methods in detail in the paper. Do your reported results[6, 7, 12] use pretrained weights from open code without additional training or train your own dataset??
 
Q2. Do you have planned to share the pretraining models with the evaluation code for Table1, 2, 3??
It would be really helpful.

**Comment by yenchenlin** [comment]
Hello @taeyeop-lee , thanks for raising these questions!!

Answer to Q1: I didn't perform additional training for [6, 7, 12] as we mentioned in the paper:

>  we consider several off-the-shelf learned descriptors ...

However, I think our method is totally compatible with [6, 7, 12], i.e., one can use data generated by NeRF-Supervision to fine-tune these descriptors and I believe the performance will be equally good if not better (as they published a few years after Florence et al. which is the descriptor model we used in this paper).

Answer to Q2: Currently I am not planning to release the pre-trained models for Tables 1, 2, and 3. The major reason is that I am using a private branch of [pytorch-dense-correspondence](https://github.com/RobotLocomotion/pytorch-dense-correspondence). I don't own the code and I don't plan to reimplement & maintain it.
