### ISSUE TITLE
Additional Datasets

### ISSUE THREAD

**Issue by dbadrian** [yenchenlin/nerf-supervision-public#7]
Hi Lin,

it seems only the fork dataset is provided so far. Are you planning releasing/uploading the other datasets in the near future?

Best
DBA

**Comment by yenchenlin** [comment]
Not really, may I know which one you are interested in and your usage?

**Comment by dbadrian** [comment]
The other two datasets, strainer and whisk, used to produce table I-III.

The intended usage is reproducing the reported results and potentially evaluating/comparing to other methods.
If the annotated correspondence points also exists, that would also be interesting.

**Comment by yenchenlin** [comment]
Sorry for the late reply. At this moment, I don't have a plan to release those due to the time constraint.
